#include "devai/features/StockBenchmarkFeatureEngine.hpp"
#include <cmath>
#include <stdexcept>
#include <utility>
namespace devai::features {
StockBenchmarkFeatureEngine::StockBenchmarkFeatureEngine(std::string s,std::string b):stock_symbol_(std::move(s)),benchmark_symbol_(std::move(b)){if(stock_symbol_.empty()||benchmark_symbol_.empty())throw std::invalid_argument("Stock/benchmark symbol cannot be empty.");if(stock_symbol_==benchmark_symbol_)throw std::invalid_argument("Stock and benchmark symbols must be different.");}
double StockBenchmarkFeatureEngine::difference(double s,double b) noexcept{return std::isfinite(s)&&std::isfinite(b)?s-b:stockBenchmarkFeatureNaN();}
double StockBenchmarkFeatureEngine::ratio(double s,double b) noexcept{if(!std::isfinite(s)||!std::isfinite(b)||b<=0.0)return stockBenchmarkFeatureNaN();double v=s/b;return std::isfinite(v)?v:stockBenchmarkFeatureNaN();}
double StockBenchmarkFeatureEngine::normalizedEMASpread(double e20,double e50) noexcept{return std::isfinite(e20)&&std::isfinite(e50)&&e50!=0.0?(e20-e50)/e50:stockBenchmarkFeatureNaN();}
RelativeDifference StockBenchmarkFeatureEngine::makeDifference(double s1,bool hs1,double b1,bool hb1,double s5,bool hs5,double b5,bool hb5,double s15,bool hs15,double b15,bool hb15) noexcept{RelativeDifference o;auto f=[](double s,bool hs,double b,bool hb,double& v,bool& h){if(hs&&hb){double x=difference(s,b);if(std::isfinite(x)){v=x;h=true;}}};f(s1,hs1,b1,hb1,o.one_minute,o.has_one_minute);f(s5,hs5,b5,hb5,o.five_minute,o.has_five_minute);f(s15,hs15,b15,hb15,o.fifteen_minute,o.has_fifteen_minute);return o;}
RelativeRatio StockBenchmarkFeatureEngine::makeRatio(double s1,bool hs1,double b1,bool hb1,double s5,bool hs5,double b5,bool hb5,double s15,bool hs15,double b15,bool hb15) noexcept{RelativeRatio o;auto f=[](double s,bool hs,double b,bool hb,double& v,bool& h){if(hs&&hb){double x=ratio(s,b);if(std::isfinite(x)){v=x;h=true;}}};f(s1,hs1,b1,hb1,o.one_minute,o.has_one_minute);f(s5,hs5,b5,hb5,o.five_minute,o.has_five_minute);f(s15,hs15,b15,hb15,o.fifteen_minute,o.has_fifteen_minute);return o;}
RelativeEMARelationship StockBenchmarkFeatureEngine::makeEMARelationship(const TrendMomentumFeatures&s,const TrendMomentumFeatures&b) noexcept{RelativeEMARelationship o;auto f=[](const auto&s,const auto&b,double&v,bool&h){if(s.has_ema20&&s.has_ema50&&b.has_ema20&&b.has_ema50){double x=difference(normalizedEMASpread(s.ema20,s.ema50),normalizedEMASpread(b.ema20,b.ema50));if(std::isfinite(x)){v=x;h=true;}}};f(s.one_minute,b.one_minute,o.one_minute,o.has_one_minute);f(s.five_minute,b.five_minute,o.five_minute,o.has_five_minute);f(s.fifteen_minute,b.fifteen_minute,o.fifteen_minute,o.has_fifteen_minute);return o;}
void StockBenchmarkFeatureEngine::validateInputs(const PriceReturnFeatures&sp,const TrendMomentumFeatures&st,const VolatilityFeatures&sv,const PriceReturnFeatures&bp,const TrendMomentumFeatures&bt,const VolatilityFeatures&bv) const{if(sp.symbol!=stock_symbol_||st.symbol!=stock_symbol_||sv.symbol!=stock_symbol_)throw std::invalid_argument("StockBenchmarkFeatureEngine stock symbol mismatch.");if(bp.symbol!=benchmark_symbol_||bt.symbol!=benchmark_symbol_||bv.symbol!=benchmark_symbol_)throw std::invalid_argument("StockBenchmarkFeatureEngine benchmark symbol mismatch.");auto t=sp.decision_time;if(st.decision_time!=t||sv.decision_time!=t||bp.decision_time!=t||bt.decision_time!=t||bv.decision_time!=t)throw std::invalid_argument("StockBenchmarkFeatureEngine decision-time mismatch.");}
StockBenchmarkFeatures StockBenchmarkFeatureEngine::update(const PriceReturnFeatures&sp,const TrendMomentumFeatures&st,const VolatilityFeatures&sv,const PriceReturnFeatures&bp,const TrendMomentumFeatures&bt,const VolatilityFeatures&bv) const{validateInputs(sp,st,sv,bp,bt,bv);StockBenchmarkFeatures o;o.stock_symbol=stock_symbol_;o.benchmark_symbol=benchmark_symbol_;o.decision_time=sp.decision_time;
o.relative_return=makeDifference(sp.one_minute_return,sp.has_one_minute&&std::isfinite(sp.one_minute_return),bp.one_minute_return,bp.has_one_minute&&std::isfinite(bp.one_minute_return),sp.five_minute_return,sp.has_five_minute&&std::isfinite(sp.five_minute_return),bp.five_minute_return,bp.has_five_minute&&std::isfinite(bp.five_minute_return),sp.fifteen_minute_return,sp.has_fifteen_minute&&std::isfinite(sp.fifteen_minute_return),bp.fifteen_minute_return,bp.has_fifteen_minute&&std::isfinite(bp.fifteen_minute_return));
o.relative_rsi14=makeDifference(st.one_minute.rsi14,st.one_minute.has_rsi14,bt.one_minute.rsi14,bt.one_minute.has_rsi14,st.five_minute.rsi14,st.five_minute.has_rsi14,bt.five_minute.rsi14,bt.five_minute.has_rsi14,st.fifteen_minute.rsi14,st.fifteen_minute.has_rsi14,bt.fifteen_minute.rsi14,bt.fifteen_minute.has_rsi14);o.relative_ema_relationship=makeEMARelationship(st,bt);
o.relative_ema20_slope=makeDifference(st.one_minute.ema20_slope,st.one_minute.has_ema20_slope,bt.one_minute.ema20_slope,bt.one_minute.has_ema20_slope,st.five_minute.ema20_slope,st.five_minute.has_ema20_slope,bt.five_minute.ema20_slope,bt.five_minute.has_ema20_slope,st.fifteen_minute.ema20_slope,st.fifteen_minute.has_ema20_slope,bt.fifteen_minute.ema20_slope,bt.fifteen_minute.has_ema20_slope);
o.relative_ema50_slope=makeDifference(st.one_minute.ema50_slope,st.one_minute.has_ema50_slope,bt.one_minute.ema50_slope,bt.one_minute.has_ema50_slope,st.five_minute.ema50_slope,st.five_minute.has_ema50_slope,bt.five_minute.ema50_slope,bt.five_minute.has_ema50_slope,st.fifteen_minute.ema50_slope,st.fifteen_minute.has_ema50_slope,bt.fifteen_minute.ema50_slope,bt.fifteen_minute.has_ema50_slope);
o.relative_atr14_percent=makeRatio(sv.one_minute.atr14_percent,sv.one_minute.has_atr14_percent,bv.one_minute.atr14_percent,bv.one_minute.has_atr14_percent,sv.five_minute.atr14_percent,sv.five_minute.has_atr14_percent,bv.five_minute.atr14_percent,bv.five_minute.has_atr14_percent,sv.fifteen_minute.atr14_percent,sv.fifteen_minute.has_atr14_percent,bv.fifteen_minute.atr14_percent,bv.fifteen_minute.has_atr14_percent);
o.relative_realized_volatility_20=makeRatio(sv.one_minute.realized_volatility_20,sv.one_minute.has_realized_volatility_20,bv.one_minute.realized_volatility_20,bv.one_minute.has_realized_volatility_20,sv.five_minute.realized_volatility_20,sv.five_minute.has_realized_volatility_20,bv.five_minute.realized_volatility_20,bv.five_minute.has_realized_volatility_20,sv.fifteen_minute.realized_volatility_20,sv.fifteen_minute.has_realized_volatility_20,bv.fifteen_minute.realized_volatility_20,bv.fifteen_minute.has_realized_volatility_20);
o.core_features_ready=o.relative_return.has_one_minute&&o.relative_return.has_five_minute&&o.relative_return.has_fifteen_minute&&o.relative_rsi14.has_one_minute&&o.relative_rsi14.has_five_minute&&o.relative_rsi14.has_fifteen_minute&&o.relative_ema_relationship.has_one_minute&&o.relative_ema_relationship.has_five_minute&&o.relative_ema_relationship.has_fifteen_minute;return o;}
} // namespace devai::features
